Repository CSPM-OpenSource-Competition-Project/CSPM-Opensource-Server, pull requests merged in 2024-08, with the labels that each got.

#14 Feat create security #5
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/elastic/cspm/CspmApplication.java
  src/main/java/com/elastic/cspm/config/MailConfig.java
  src/main/java/com/elastic/cspm/config/SecurityConfig.java
  src/main/java/com/elastic/cspm/config/SwaggerConfig.java
  src/main/java/com/elastic/cspm/controller/AccountController.java
  src/main/java/com/elastic/cspm/data/dto/InfoResponseDto.java
  src/main/java/com/elastic/cspm/data/dto/SignupDto.java
  src/main/java/com/elastic/cspm/data/entity/ErrorLog.java
  src/main/java/com/elastic/cspm/data/entity/IAM.java
  src/main/java/com/elastic/cspm/data/entity/Member.java
  src/main/java/com/elastic/cspm/data/entity/Policy.java
  src/main/java/com/elastic/cspm/data/repository/GroupRepository.java
  src/main/java/com/elastic/cspm/data/repository/IamRepository.java
  src/main/java/com/elastic/cspm/data/repository/MemberRepository.java
  src/main/java/com/elastic/cspm/service/AccountService.java
  src/main/java/com/elastic/cspm/service/EmailService.java
  src/main/java/com/elastic/cspm/utils/Length.java
  src/main/resources/application-dev.yml
  src/main/resources/properties/env.properties
Labels: ✨Feature

#22 fix: Iam Table add nickName
  src/main/java/com/elastic/cspm/data/entity/IAM.java
  src/main/java/com/elastic/cspm/data/entity/Member.java
  src/main/java/com/elastic/cspm/service/AccountService.java
Labels: 🕷 BugFix

#20 setting: yml에서 aws credential region 서울로 설정 /#17
  src/main/resources/application-dev.yml
Labels: ✨Feature

#25 Fix#23 secrityconfig
  src/main/java/com/elastic/cspm/config/SecurityConfig.java
  src/main/java/com/elastic/cspm/controller/ReissueController.java
  src/main/java/com/elastic/cspm/data/dto/CustomUserDetails.java
  src/main/java/com/elastic/cspm/data/dto/LoginRequestDto.java
  src/main/java/com/elastic/cspm/data/entity/RefreshEntity.java
  src/main/java/com/elastic/cspm/data/repository/RefreshRepository.java
  src/main/java/com/elastic/cspm/jwt/CustomLogoutFilter.java
  src/main/java/com/elastic/cspm/jwt/JWTFilter.java
  src/main/java/com/elastic/cspm/jwt/JWTUtil.java
  src/main/java/com/elastic/cspm/jwt/LoginFilter.java
  src/main/java/com/elastic/cspm/service/CustomUserDetailsService.java
  src/main/java/com/elastic/cspm/service/RefreshService.java
  src/main/resources/application-dev.yml
Labels: 🕷 BugFix, ✨Feature

#27 feat#26-스케줄링 성공
  build.gradle
  src/main/java/com/elastic/cspm/CspmApplication.java
  src/main/java/com/elastic/cspm/config/SecurityConfig.java
  src/main/java/com/elastic/cspm/data/entity/Member.java
  src/main/java/com/elastic/cspm/data/entity/RefreshEntity.java
  src/main/java/com/elastic/cspm/data/repository/RefreshRepository.java
  src/main/java/com/elastic/cspm/jwt/LoginFilter.java
  src/main/java/com/elastic/cspm/service/RefreshService.java
  src/main/java/com/elastic/cspm/service/SchedulingRefreshService.java
Labels: ✨Feature

#33 Feat#30 scangroup
  src/main/java/com/elastic/cspm/controller/DashboardController.java
  src/main/java/com/elastic/cspm/controller/ResourceController.java
  src/main/java/com/elastic/cspm/data/dto/ResponseScanGroupDto.java
  src/main/java/com/elastic/cspm/data/dto/ScanGroupDto.java
  src/main/java/com/elastic/cspm/data/entity/BridgeEntity.java
  src/main/java/com/elastic/cspm/data/entity/Member.java
  src/main/java/com/elastic/cspm/data/entity/ScanGroup.java
  src/main/java/com/elastic/cspm/data/repository/BridgeEntityRepository.java
  src/main/java/com/elastic/cspm/data/repository/GroupRepository.java
  src/main/java/com/elastic/cspm/data/repository/ScanGroupRepository.java
  src/main/java/com/elastic/cspm/data/repository/impl/ResourceRepositoryCustomImpl.java
  src/main/java/com/elastic/cspm/service/AccountService.java
  src/main/java/com/elastic/cspm/service/DashboardService.java
  src/main/java/com/elastic/cspm/service/RefreshService.java
  src/main/java/com/elastic/cspm/service/ScanGroupService.java
  src/main/resources/application-dev.yml
  src/main/resources/data.sql
Labels: ✨Feature

#40 feat: 계정 비밀번호 변경 API 구현/#38
  src/main/java/com/elastic/cspm/controller/AccountController.java
  src/main/java/com/elastic/cspm/controller/IamsettingController.java
Labels: ✨Feature

#42 feat: IAM 삭제 /#38
  src/main/java/com/elastic/cspm/controller/IamsettingController.java
  src/main/java/com/elastic/cspm/service/IamService.java
Labels: ✨Feature

#43 FIX/#34 Runtime 에러 긴급 수정
  src/main/java/com/elastic/cspm/data/entity/DescribeResult.java
  src/main/resources/data.sql
Labels: 🕷 BugFix

#44 Feat#36 scan graph api
  src/main/java/com/elastic/cspm/controller/DashboardController.java
  src/main/java/com/elastic/cspm/data/dto/GrapComplianceDto.java
  src/main/java/com/elastic/cspm/data/dto/GraphScanDto.java
  src/main/java/com/elastic/cspm/data/repository/ComplianceRepository.java
  src/main/java/com/elastic/cspm/data/repository/DescribeResultRepository.java
  src/main/java/com/elastic/cspm/jwt/JWTFilter.java
  src/main/java/com/elastic/cspm/service/DashboardService.java
  src/main/java/com/elastic/cspm/utils/GroupColor.java
Labels: ✨Feature

#45 Fix: iam 반환 로직 email 추가하여 변경
  src/main/java/com/elastic/cspm/controller/ResourceController.java
  src/main/java/com/elastic/cspm/data/repository/IamRepository.java
  src/main/java/com/elastic/cspm/service/IamService.java
Labels: ✨Feature

#46 feat: GET scanGroup API fix/scanGroup
  src/main/java/com/elastic/cspm/controller/ResourceController.java
  src/main/java/com/elastic/cspm/service/ScanGroupService.java
Labels: ✨Feature
